swoocn/map-of-pi

backend/server.js, package.json
Build consolidated package.json for Netlify integration and deployment; fix /backend paths.
=> Netlify Integration and Deployment

package-lock.json, package.json
=> Netlify Integration and Deployment setup

backend/.env, package-lock.json, package.json
=> Configure root config file to fix Netlify Integration and Deployment.

netlify.toml
=> Build netlify.toml to consolidate frontend + backend configuration.

frontend/src/app/shop/order-menu/order-menu.component.html, frontend/src/app/shop/order-menu/order-menu.component.ts, frontend/src/assets/styles/shop/order-menu/main.scss
Resolve HTML with properties/ binding and Angular component; adjust styles based on local testing.
=> Resolve HTML with properties/ binding and Angular component; adjust styles based on local testing.

README.md, frontend/src/app/shared/header/header.component.html, frontend/src/app/shared/header/header.component.scss, frontend/src/app/shared/header/header.component.ts
Header logo effect revisited & readme updates.
=> Header logo effect revisited & readme updates.

frontend/src/app/business/business-settings/business-settings.component.html, frontend/src/app/home/map/map.component.scss, frontend/src/app/shared/header/header.component.html, frontend/src/app/shared/header/header.component.scss, frontend/src/app/shared/header/header.component.ts, frontend/src/app/shared/language-switcher/language-switcher.component.ts, frontend/src/assets/i18n/de.json, frontend/src/assets/i18n/en.json, frontend/src/assets/i18n/es.json, frontend/src/assets/i18n/hu.json, frontend/src/assets/i18n/ko.json, frontend/src/assets/styles/business/business-menu/modal.scss, frontend/src/assets/styles/business/business-settings/popup.scss
=> Wrap up elements #1

frontend/src/app/shared/header/header.component.html, frontend/src/styles.scss
=> Additional style adjustments.

frontend/src/app/business/manage-business/manage-business.component.html, frontend/src/app/dialogs/information/information.component.html, frontend/src/app/dialogs/information/information.component.scss, frontend/src/app/dialogs/information/information.component.ts, frontend/src/app/shared/footer/footer.component.html
Misc footer & information popup adjustments.
=> Misc footer & information popup adjustments.

frontend/src/app/business/business-settings/business-menu/business-menu.component.html, frontend/src/app/business/business-settings/business-menu/business-menu.component.ts, frontend/src/app/dialogs/information/information.component.ts, frontend/src/app/shared/header/header.component.html, frontend/src/app/shared/header/header.component.spec.ts, frontend/src/assets/i18n/en.json, frontend/src/assets/i18n/es.json, frontend/src/assets/i18n/ko.json
=> Additions & Revisions #3

frontend/src/app/business/business-settings/business-settings.component.html, frontend/src/app/business/business-settings/business-settings.component.ts
Commented out parts related to phone and email registration in business registration screen.
=> Comment out syntax related to phone and email registration

frontend/src/app/dialogs/information/information.component.ts, frontend/src/app/home/home.component.html, frontend/src/app/home/home.component.ts, frontend/src/app/home/map/map.component.ts, frontend/src/app/home/search-bar/search-bar.component.html, frontend/src/app/home/search-bar/search-bar.component.ts
=> Implemented basic search functionality; updated Info Dialog accordingly.

frontend/src/app/home/map/map.component.ts, frontend/src/app/home/map/marker-options.interface.ts
Fix issue due to search and language translation clearing and replacing all and filtered map markers.
=> Utilize currentUser flag to prevent removing user marker.

frontend/src/app/app.component.html, frontend/src/app/business/manage-business/add-product/add-product.component.scss, frontend/src/app/business/manage-business/manage-business.component.html, frontend/src/app/dialogs/information/information.component.html, frontend/src/app/dialogs/information/information.component.scss, frontend/src/app/dialogs/information/information.component.spec.ts, frontend/src/app/dialogs/information/information.component.ts, frontend/src/app/home/action-row/action-row.component.html, frontend/src/app/shared/header/header.component.html, frontend/src/app/shared/privacy-policy/privacy-policy.component.scss, frontend/src/app/shared/terms-of-service/terms-of-service.component.scss, frontend/src/assets/styles/business/business-settings/main.scss, frontend/src/assets/styles/shop/order-menu/main.scss
=> Social media popup and removal of footer; prep for dashboard.

frontend/src/app/business/business-settings/business-settings.component.html, frontend/src/app/business/business-settings/business-settings.component.ts
Revert email field due to broken backend process.
=> Revert email field due to broken backend process.

frontend/src/app/business/business-settings/business-settings.component.ts
Business types lang translation in the Business Registration screen.
=> Business types lang translation in the Business Registration screen.

frontend/src/app/business/business-settings/business-settings.component.html, frontend/src/app/business/business-settings/business-settings.component.ts, frontend/src/app/home/map/map.component.ts, frontend/src/app/shared/header/header.component.html, frontend/src/assets/styles/business/business-settings/main.scss, frontend/src/assets/styles/business/business-settings/popup.scss, frontend/src/assets/styles/themes/dark-mode/dark-template.scss, frontend/src/assets/styles/themes/light-mode/light-template.scss, frontend/src/styles.scss
=> Dark mode redux WIP and bug fixes.

frontend/src/app/business/business-settings/business-menu/business-menu.component.html, frontend/src/app/shop/order-menu/order-menu.component.html, frontend/src/app/shop/order-menu/order-menu.component.scss, frontend/src/app/shop/order-menu/order-menu.component.ts, frontend/src/assets/styles/business/business-menu/main.scss, frontend/src/assets/styles/business/business-menu/modal.scss, frontend/src/assets/styles/shop/order-menu/main.scss, frontend/src/styles.scss
=> Apply dark mode to shopping order menu; minor revisions.

frontend/src/app/core/service/geolocation.service.ts
=> Fixed zooming out issue to the point of seeing map tiles.

frontend/src/app/core/service/geolocation.service.ts
=> Fix bugs (WIP)

frontend/src/app/home/action-row/action-row.component.ts, frontend/src/app/home/map/map.component.ts
Fix runtime bugs + remove 'noise' in console.
=> Fix runtime bugs + remove 'noise' in console.

frontend/src/app/home/map/map.component.ts, frontend/src/index.html
=> Fix 'L' Reference error; cleanup unnecessary console logging.

frontend/src/app/home/action-row/action-row.component.ts, frontend/src/app/home/map/map.component.ts, frontend/src/index.html
=> Propagate latest bug fixes for deployment.

frontend/src/app/home/map/map.component.ts, frontend/src/styles.scss
=> Fix bugs WIP
